travis:
  secure:
    BINSTAR_TOKEN: BHy1poEemcMv13TANTIbeO72X70j+r7ddwj/fDJjpYfqE/yQIlAEriEOL87MODkJ2mGCem9CnMUnWi1m8I5zEB4YVl521N6gMhPEgxuFhPvMtlQQS4H0+pN6YF6bB/xG4cGrIks7cpViTwYvlbF90ihiJYkvMq+/Kl0OA7BwvXYzX+A4qRIh+ecnJWvYL7y4AQQONVc7esV5OitKVCdac1AzDu0/GcSDvn4vwWwuOsmSmxpxjUrdRpFuuNjm94zqJ7cuGgfcnV6TGS6qayUtb2ww1zBo8sTjzIoHxXJMFA9zJRT3Tp3XkPZuMU2LomhXKr5UfoA0CHC0AYmCdrfZLl1kM1OpYP/ZjSqLVR+6HuKgP4N80adDfDgi8Zn++YTWnfIAeUbYcfEB+fbsJrohVEqAuDeY3RezyWJqYCGf+COIqE92gKlLH70H2vtTQKhxI53/ZQ77cbYyKez+DLMWPdcWPhZ98nFTEtZHaDSyQif7HRuGs0uvTL3B1C54SMjHA1HR+tEqE8utRSaOWypkSXCj8mRuwgNfsUKFW3ldvpo0CIn4Y3517j5oG5q+Z/EUjjPbCP1AI7drRPCoX4H8vsQU4LpbgfyZxQiimuMg4d7Igi+zIbEvwJnYnzu4VBO3jYEuiAKtooEhzN2JcICNqfwvIy1XrbRUPAEcNPJ5qlg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
