travis:
  secure:
    BINSTAR_TOKEN: 44rVD5HHYEH4MVOV/ujnF4HTV4oK3vW+JVBtgSEXC0ZHgy7nUfXgOIXfbHuRXXsLTLIg6QIPuwL1x73qtoQEmcqbSEzDsJRsNJyQs1cQp3CqC7yfz6M2fn1V9d+cEzljuFevTXz9lgOP1ZzFWIf1yeoRBQtt3PGxtIn2mx1ZJTWZOkWCtor/bB8QBQbdRrxaGebd0HWi5dPaV+rr3kSNQ+o2uD7bqfoAHYrOCs4xC7yuS29Ds8cjyORNypAxl94kKWYgcXdvt9Utza1tciynXZo/q3Z1XW+KnYXQJYlbx3hSdqj9lreu1DejH6KfhTh+Z0ZdNdw418ggO0lDMuBTGgkXeEDqXztGSsZ0rbi2qBkmQvl6qEqrGhPdHupvSljfMOUs4fzyfx6BQq+qwhRDNOrQeSzLNjD/C84Wba1pEQVFA1eKLQbOdKJesEqGuqBF7tU0KZe29HLhuzyhPy3nLOO4hKwg20ImoIfTCLIy4CtRXu68N/gdsLy/VU/BS0zUacuWqCJxC43IVyIwy1F+7UFG4H86PiQiWfBM5UtAzTXEkzFTywmDICn2yFGR4RuKdyhJpcWN1KNluCj2GCVOTMn/1HqdsxYumeLqRtrnTisK0eaYCHaoYkxaoSyNkhPNY1GV07oWWvfjy1BtbmmxZxzuNEZIMq1x0UnOX/Ou4GM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
